export const randomPrompts = [
  "A futuristic tech startup logo with geometric patterns and gradient colors",
  "An elegant restaurant logo featuring hand-drawn culinary elements and sophisticated typography",
  "A modern clothing brand logo with minimalist design and subtle texture",
  "A warm and inviting coffee shop logo with artisanal details and organic shapes",
  "A dynamic startup logo combining abstract shapes with vibrant color transitions",
  "A prestigious law firm logo with classic serif typography and symbolic elements",
  "A clean tech company logo with innovative iconography and balanced negative space",
  "A wanderlust-inspiring travel agency logo with worldly motifs and flowing lines",
  "A luxury jewelry brand logo with intricate details and metallic accents",
  "A sustainable eco-friendly company logo incorporating natural elements and earthy tones",
  "A bold fitness brand logo with dynamic movement and energetic typography",
  "A creative photography studio logo with aperture symbolism and artistic flair",
  "A sophisticated financial services logo conveying trust and stability through geometric precision",
  "A playful children's education brand logo with whimsical characters and bright colors",
  "A premium automotive company logo with sleek lines and metallic gradients",
  "A healthcare provider logo balancing professional authority with compassionate design elements",
  "A cutting-edge AI company logo with neural network patterns and futuristic aesthetics",
  "A handcrafted artisanal bakery logo with wheat motifs and vintage typography",
  "A modern architecture firm logo with structural elements and minimalist composition",
  "A vibrant entertainment company logo with dynamic shapes and cinematic elements",
];
